mobile to desktop version
PowerLevel9000/portfolio-project pull request #6
Opened 2022-12-15 04:30 UTC by PowerLevel9000

making responsive to desktop version and mobile version in future there will be a tablet version

2022-12-16 05:12 UTC, emmiiorji requested changes
Hi @PowerLevel9000, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![A little bit more](https://user-images.githubusercontent.com/20554583/208024081-6d35a6f8-51db-4125-a035-ae4e78555a2e.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 05:12 UTC, emmiiorji commented on styles.css
> +  }
Kindly modify the languages section to be similar to the figma design.

Note the following:

- The arrow on figma design is lighter than on your design
- The icons has more passing on the figma design than your design
- You're missing the horizontal lines
- There's more margin on the figma design between the arrows and the container than on your design

Your design:
![image](https://user-images.githubusercontent.com/20554583/208024940-ba25ccb4-cb66-463e-8195-a457f185b739.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/208024905-c2f31bdf-5452-4a5f-a541-1231f3ad8002.png)

2022-12-16 05:12 UTC, emmiiorji commented on styles.css
> +  }
Please, modify the project cards to match the design as closely as possible. Kindly ensure that the description takes up the correct width as shown on the design. Also the list of technologies are left aligned.

Your design:
![image](https://user-images.githubusercontent.com/20554583/208026184-af412462-6b69-4933-bd8c-6d14b24c1462.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/208026156-2b00471e-d82e-4997-97c1-e85f4e73df48.png)

2022-12-16 05:12 UTC, emmiiorji commented on styles.css
> +@media screen and (min-width: 376px) {
Kindly ensure that the mobile version remains responsive until the desktop screen size (768px). This means that the value for the min-width property should be 768px or above. This screen sizes below are supposed to display as mobile.

Your design below 768px:
![image](https://user-images.githubusercontent.com/20554583/208026765-d12b08a1-0fde-4dc3-a545-e472ac1cf463.png)

Your design at 515px:
![image](https://user-images.githubusercontent.com/20554583/208027030-431b7627-362f-4483-9d8d-2634f5e87f77.png)

2022-12-16 07:40 UTC, binhussen approved these changes
Hi @PowerLevel9000 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg"/>
## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 09:37 UTC, merged

2022-12-16 10:09 UTC, kingnoel commented
Congratulations!!!

2023-05-21 03:01 UTC, PowerLevel9000 commented
# Thank you 💪💪💪🙏🙏🙏

![ThankYouSoMuchPrabhasGIF](https://user-images.githubusercontent.com/116451144/233258767-f3943ca4-fbe2-4fde-b8b1-2129593266e5.gif)


Dear @emmiiorji @binhussen ,

I wanted to express my gratitude for your willingness to take the time to review my code on GitHub. Your feedback and suggestions have been instrumental in improving the quality of my work, and I appreciate your insights and expertise in this area.

It's inspiring to have someone like you, who is knowledgeable and experienced, provide valuable feedback that helps me enhance my coding skills. I truly appreciate the time and effort you put into reviewing my code, and I'm grateful for your constructive criticism.

If there are any areas that I need to work on, please don't hesitate to let me know. I'm open to hearing any suggestions or recommendations you may have. Your feedback is essential to my growth as a developer, and I value it tremendously.

Thank you again for your time and for sharing your expertise with me. I'm looking forward to applying the insights gained from your review to my future projects.

Sincerely,
@PowerLevel9000